/**
 * Portraits, 48 x 48: a bust on a dark tinted disc, one clear expression each.
 * Sketched shape by shape (head, ears, snout, hat placed by hand), finished
 * pixel by pixel, and kept as rows of characters with a legend of their own
 * like every other sprite, on the 48 x 48 square (the bottom row is where the
 * frame cuts the bust). `portraits.ts` lays the disc behind and adds the
 * outline. Light from the upper left; people's eyes mirror each other with
 * the iris centred.
 *
 * Menace by silhouette and attitude, never gore; funny is welcome, cute is not.
 */
import type { Legend } from './grid';
import type { Shade } from './palette';

export interface FaceDef {
  readonly rows: readonly string[];
  readonly legend: Legend;
  /** The disc behind the bust: its tint, and the rim where it catches the light. */
  readonly disc: readonly [Shade, Shade];
}

export const FACES: Readonly<Record<string, FaceDef>> = {
  // A dock rat, very sure of itself: beady eyes under brows slanting in, a crooked grin
  // with teeth on one side, paws rubbing together, a bite out of one ear.
  dock_rat: {
    rows: [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '..........aaaa...................aaaa',
      '........aaaaaaaa...............aaaaaaaa',
      '.......aaaaaaaaaa.............aaaaaaaaaa',
      '.......aaaqqqqqaa.............aaqqqqqaaa',
      '......aaaqqqqqqqaa...........aaqqqqqqqa',
      '......aaaqqqqqqqaa.....a.....aaqqqqqqqa',
      '......aaaqqqqqqqaa.aaaaaaaaa.aaqqqqqqqcc',
      '......aaaqqqqqqqaaaaaaaaaaaaaaaqqqqqqqccc',
      '.......aaqqqqqqqaaaaaaaaaaaaaaaqqqqqqqcc',
      '.......aaaqqqqqaaaaaaaaaaaaaaaaaqqqqqccc',
      '........aaaqqaaaaaaaaaaaaaaaaaaaaaqqccc',
      '..........aaaaaacaaaaaaaaaaaaaacaaccc',
      '.............aaacccaaaaaaaaaacccac',
      '.............aaaaaccaaaaaaaaccaacc',
      '.............aaaawkkaaaaaaaawkkacc',
      '.............aaaakkkaaaaaaaakkkccc',
      '.............aaaakkkaaaaaaaakkkccc',
      '..............aaaaaaaaaaaaaaaaacc',
      '..............aaaaaaaaaaaaaaaaacc',
      '...............aaaaaaaaaaaaaaaac',
      '................aaaaaaaaaaaaaaa',
      '................aaaaaaaaaaaaaaa',
      '.................aalllllllllaa',
      '...........EEE...aalllllllllaa....EEE',
      '..............EEE.allllllllla..EEE',
      '.................EEElllllllaEEE',
      '..................aalllllllcc',
      '...............EEEEElllllllcEEEEE',
      '...........EEEE....allpppllc.....EEEE',
      '....................lpwpppl..c',
      '...................cccpppcccc',
      '...............aaccccccccceecccc',
      '.............aaacccccceeEccccccccc',
      '............aaaccccccleeElccccccccc',
      '...........aaaccccclllllllllcccccccc',
      '..........aaaacccclllllllllllcccccccc',
      '.........aaaaccccllppplllpppllcccccccc',
      '........aaaaccccclpwppplpwppplccccccccc',
      '........aaacccccclpppppPpppppPccccccccc',
      '........aacccccccllppplllpppllccccccccc',
      '........acccccccclllllllllllllccccccccc',
    ],
    legend: {
      a: 'oakbark1',
      b: 'oakbark2',
      c: 'oakbark3',
      l: 'cobble1',
      p: 'flush1',
      P: 'flush2',
      q: 'lips1',
      k: 'ink1',
      w: 'white1',
      e: 'plaster1',
      E: 'plaster2',
    },
    disc: ['slate3', 'slate2'],
  },
  // A sand crab with opinions: eyes on stalks under furious lids, one claw raised and
  // open, the other wagged, a small cross mouth.
  sand_crab: {
    rows: [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '......a',
      '....aaa...aaa',
      '....aaa...aaa',
      '...aaaaa..aaaa',
      '...aaaaa..aaac',
      '...aaaaa..aaac',
      '...aaaaa..aacc..cc............cc',
      '...aaaaaaaaacc..ccccc......ccccc',
      '...aaaaaaaaacc..bbccccc..cccccbb',
      '...aaaaaaaaacc...wbbbcc..ccbbbw',
      '...aaaaaaaaccc...wwwkbb..bbkwww',
      '....aaaaaaccc.....wwk......kww',
      '....aaacccccc......aa.......aa',
      '......ccccc........aa.......aa',
      '........ccc........aa.......aa...........a',
      '........cccc.......aa.......aa.......aa..bbb',
      '.........ccc.......aa.......aa.......abb.bbb',
      '.........cccc......ac.......ac......aabb.bbbc',
      '..........ccc......ac.......ac......abbb.bbcc',
      '..........cccc.....aa..a....ab......abbbbbbcc',
      '..........cccc...aaaaaaaaaabbb......bbbbbbbcc',
      '...........cccaaaaaaaaaaaabbbbbbb....bbbbbcc',
      '...........ccaaaaaaabbbbbbbbbbbbbb...bbbcccc',
      '...........aaaaaabcbbbbbbbbbbbbbbbbb..bccc',
      '..........aaaaabbbbbbbbbbbbcbbbbbbbbbcccc',
      '..........aaaabcbbbbbbbbbbbbbbbbbbbccccc',
      '.........aaaabbbbbbbbbbbbbbbbbbbbbccccc',
      '.........aaaabbbbbbbbcbbbbbbbbbcbcccccc',
      '.........aaaabbbbbbbbbbbbbbbbbbbbccccc',
      '.........aaaabbbbbbbbbbbbbbbbbbbbccccc',
      '.......aaaaabbbbbbbbbbbbbbbbbbbbbcccccc',
      '.....aaccabbbbbbbbbsssssssssbbbbbcccccccc',
      '...aacc...bbbbbbssssskkkkkkssssbccccc..cccc',
      '...cc...bbbbbbsssssskssssssksssssccccc...cccc',
      '.......bcc.bbssssssssssssssssssssscc.ccc...cc',
      '.....bbc.....sssssssssssssssssssss....ccc',
      '....bcc.......sssssssssssssssssss.......ccc',
      '....c............sssssssssssss...........ccc',
      '.......................s...................c',
    ],
    legend: { a: 'red1', b: 'red2', c: 'red3', s: 'sand2', k: 'ink1', w: 'white1' },
    disc: ['teal2', 'teal1'],
  },
  // A thieving gull turned to glare back at us, a stolen chip in its beak, its pale eye
  // ringed in red under a furious brow.
  thieving_gull: {
    rows: [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '.........................w',
      '.....................wwwwwwwww',
      '...................wwwwwwwwwwwww',
      '.................tttwwwwwwwwwwwww',
      '.................wwtttttwwwwwwwwww',
      '................wwwrrtttttwwwwwwwww',
      '........hh......wwwrrrrwttwwwwwwwww',
      '........hH.....wwwrrhkrrwwwwwwwwwwww',
      '........hH.....wwwwrhhrwwwwwwwwwwwww',
      '........hH...yyywwwrrrrwwwwwwwwwwwww',
      '........hHyyyyyywwwwwwwwwwwwwwwwwwww',
      '....yyyyhHyyyyyywwwwwwwwwwwwwwwwwwww',
      '..yyyyyyhHyyyyyywwwwwwwwwwwwwwwwwwww',
      '..YYYYYYhHYYYYYYwwwwwwwwwwwwwwwwwww',
      '......YrhHYYYYYYwwwwwwwwwwwwwwwwwww',
      '.......rhH.......wwwwwwwwwwwwwwwww',
      '........hH........wwwwwwwwwwwwwww',
      '........hH.........wwwwwwwwwwwww',
      '........hH..........wwwwwwwwwwww',
      '........hH.........wwwwwwwwwwwwww',
      '........HH.........wwwwwwwwwwwwww',
      '...................wwwwwwwwwwwwww',
      '...................wwwwwwwwwwwwww',
      '....................wwwwwwwwwwwwss',
      '..................wwwwwwwwwwwwwwsssss',
      '.................wwwwwwwwwwwwwwssssggggg',
      '................wwwwwwwwwwwwwwsssgggggggggg',
      '...............wwwwwwwwwwwwwwwsssggggggggggg',
      '..............wwwwwwwwwwwwwwwwssgggggggggggg',
      '.............wwwwwwwwwwwwwwwwwssgggggggggggg',
      '.............wwwwwwwwwwwwwwwwwsgggggggggggggt',
      '.............wwwwwwwwwwwwwweeeggggggggggggggt',
      '............wwwwwwwwwwwwweeeeeggggggggggggggt',
      '............wwwwwwwwwwwweeeeeeggggggggkkgggtt',
      '............wwwwwwwwwwweeeeeeegggggggkkkkkkkk',
      '............wwwwwwwwwweeeeeeeegggggggkkkkkkkkkk',
      '............wwwwwwwwweeeeeeeeegggggggkkkkekkkkk',
      '............wwwwwwwweeeeeeeeeegggggtkkkkkkkkekk',
      '.............wwwwwwweeeeeeeeeeggggttkkkkkkkkkkk',
    ],
    legend: {
      w: 'white1',
      e: 'stone1',
      s: 'stone1',
      g: 'stone2',
      t: 'stone3',
      k: 'ink1',
      y: 'gold1',
      Y: 'gold2',
      r: 'red1',
      h: 'plaster1',
      H: 'sand2',
    },
    disc: ['navy1', 'slate2'],
  },
  // A bramble boar: small eyes under a glowering brow, a ridge of bristles, tusks
  // curving up past the snout, brambles caught in its hide.
  bramble_boar: {
    rows: [
      '',
      '',
      '',
      '',
      '',
      '',
      '.................g.G',
      '..................G..........Gg',
      '...............grRg.a.a.a.....GrR',
      '..............a.G.a.c.c.c.a.a.ag',
      '..............c.g.c.c.c.c.c.c.c.Gg',
      '...............G.c.cacacacac.c.cG',
      '..............Gc.cacacacacacac.c.G',
      '............aG.aaaaaaaaaaaaabbbb..G',
      '..........aaa.aaaaaaaaaaaaabbbbbb.bbb',
      '........aaaaqaaaaaaaaaaaaabbbbbbbbqbbbb',
      '.......aaaqqaaaaaaaaaaababbbbbbbbbbqqbbb',
      '.....aaaaqqqaaaaaaabbbbbbbbbbbbbbbbqqqbbcc',
      '....aaaqqqqaaaaaabbbbbbbbbbbbbbbbbbbqqqqccc',
      '.....aaaaqqaaaaabbbbbbbbbbbbbbbbbbbbqqcccc',
      '......aaaaaaaaccbbbbbbbbbbbbbbbbccbbbcccc',
      '......aaaaaaaacccccbbbbbbbbbbcccccbbccccc',
      '.......aaaaaaabbcccccbbbbbbcccccbbbccccc',
      '........a..aaabbrkkccbbbbbbccrkkbbcc..c',
      '...........aabbbkkkbbbbbbbbbbkkkbccc',
      '...........aabbbbbbbbbbbbbbbbbbbbccc',
      '............abbbbbbbbbbbbbbbbbbbbcc',
      '............abbbbbbbbbbbbbbbbbbbbcc',
      '.............bbbbbbbbbbbbbbbbbbbbc',
      '..............bbbbbbbbbbbbbbbbbbb',
      '...........e..bbbbbbbbbbbbbbbbbbb...e',
      '...........ee.bbbbbbpppPpppbbbbbb..ee',
      '...........eee.bbbbpPPPPPPPpbbbb..eee',
      '............Ee.bbbpPPPPPPPPPpbbb..eE',
      '............eEebbbpPPPPPPPPPpbbc.eEe',
      '.............EebbbpPkkPPPPkkpbcce.E',
      '.............eEebbppkkPPPPkkpcc.eEe',
      '..............eEebbpppppppppccceEe',
      '............bbeEebbbpppppppcccceEec',
      '..........bbbbGGEebcccccccccccGGecccc',
      '.........bgbGGbbbcccccccccccccccGGgccc',
      '........bbGGbbbbbcccccccccccccccccGGGcc',
      '......gbrRbgbbbbcccccccccccccccccccgrRGg',
      '......GGbbbbbbbccccccccccccccccccccccccGGGg',
      '....GGbgbbbbbbccccccccccccccccccccccccccgcGG',
      '..GG.bbbbbbbbccccccccccccccccccccccccccccc.gGG',
      '.....bbbbbbbbccccccccccccccccccccccccccccc',
      '.....bbbbbbbcccccccccccccccccccccccccccccc',
    ],
    legend: {
      a: 'hairchestnut1',
      b: 'hairchestnut2',
      c: 'hairchestnut3',
      p: 'flush2',
      P: 'flush1',
      q: 'lips2',
      k: 'ink1',
      e: 'plaster1',
      E: 'plaster2',
      g: 'pine1',
      G: 'pine2',
      r: 'red1',
      R: 'red3',
    },
    disc: ['pine3', 'pine2'],
  },
  // A grey wolf: ears pricked, amber eyes narrowed and steady, a lip drawn back from
  // one tooth. Patient, not snarling.
  grey_wolf: {
    rows: [
      '',
      '',
      '..........a.........................b',
      '..........aa.......................bb',
      '..........aaa.....................bbb',
      '...........aaa...................bbb',
      '...........aaaa.................bbbb',
      '...........aqaaa...............bbbqb',
      '...........aaqaaa.............bbbqbb',
      '...........aaqqaaa.....a.....bbbqqbb',
      '...........aaqqqaaaaaacccaaabbbqqqbb',
      '............aqqqaaaaaacccaabbbbqqqb',
      '............aqqaaaaaaacccabbbbbbqqb',
      '............aaaaaaaaabcccbbbbbbbbbb',
      '............aaaaaaabbbcccbbbbbbbbbb',
      '............aaaaaabbbbcccbbbbbbbbbb',
      '.............aaaabbbbbcccbbbbbbbbb',
      '.............aaabbbbbbcccbbbbbbbbb',
      '............aaabbbbbbbcccbbbbbbbbbb',
      '............aaabbbbbbbcccbbbbbbbbbc',
      '...........aaaakkkbbbbcccbbbbbkkkccc',
      '...........aaabbykkkbbcccbbbkkkycccc',
      '...........aaabbykybbbcccbbbbykycccc',
      '...........aaabccccbbbcccbbbbccccccc',
      '...........aaabbbbbbbbcccbbbbbbbcccc',
      '..........aaaabbbbbbbbcccbbbbbbbccccc',
      '..........aaaabbbbbbbbbbbbbbbbbbccccc',
      '..........laabbbbbbbbbbbbbbbbbbbccccl',
      '...........llbbbbbbbbbbbbbbbbbbcccll',
      '............lllbbbbbbbbbbbbbbbbclll',
      '.............ll.bbbbbbbbbbbbbbc.ll',
      '.................bblllbbblllbc',
      '.................bblllbbblllcc',
      '...............l..blllbbblllc..l',
      '..............lll.blllllllllc.lll',
      '.............llll.bblllllllcc.llll',
      '............lllllllclkkkkklclllllll',
      '............lllllllclkgkkklclllllll',
      '.............llllllllkkkkkllllllll',
      '.............lllllllllllllllllllll',
      '...........bblllllllccccccccllllllcc',
      '..........bbblllllllllllllelllllllccc',
      '.........bbbbblllllllllllllllllllccccc',
      '........bbbbbclllllllllllllllllllcccccc',
      '.......bbbbbcclllllllllllllllllllccccccc',
      '.......bbbbccclllllllllllllllllllccccccc',
      '......bbbbccccclllllllllllllllllccccccccc',
      '......bbbbccccclllllllllllllllllccccccccc',
    ],
    legend: {
      a: 'stone1',
      b: 'stone2',
      c: 'stone3',
      l: 'plaster1',
      q: 'cloth1',
      k: 'ink1',
      g: 'slate1',
      e: 'white1',
      y: 'gold1',
    },
    disc: ['dress2', 'dress1'],
  },
  // A footpad, hood up: a cocked brow, a practised smirk with a gap in it, his
  // cudgel over his shoulder.
  footpad: {
    rows: [
      '',
      '',
      '.......................H',
      '...................HHHHHHHHH',
      '.................HHHHHHHHHHHHH',
      '...............HHHHHHHHHHHHHHHHH',
      '..............HHHHHHHHHHHHHHHHHhh',
      '.............HHHHHHHHHHHHHHHHHhhhh',
      '............HHHHHHHHHHHHHHHHHhhhhhh',
      '............HHHHHHHHHHHsHHHHhhhhhhh',
      '...........HHHHHHHHHsssssssHhhhhhhhh',
      '...........HHHHHHHssssssssssshhhhhhh',
      '..........HHHHHHHdddddddddddddhhhhhhh',
      '..........HHHHHHssssssssssssssshhhhhh',
      '..........HHHHH.sssssssssssssss.hhhhh',
      '..........HHHHHsssssssssssBssssshhhhh',
      '..........HHHHHsssssssssssBBBssshhhhh....OOO',
      '..........HHHHsssBBBBBsssssssBBddhhhh...OOOOO',
      '..........HHHhssssssssssssssssdddhhhh..OOOOOOO',
      '..........HHHhsssswkwsssssswkwdddhhhh..OOqOOOq',
      '..........HHhssssswkwsssssswkwdddhdhh..OOOOOOq',
      '..........HHhsssssssssssssssssdddhdhh..OOOOOOq',
      '..........Hhhhssssssssssdsssssdddhhhh..OOOOOOq',
      '..........Hhhhssssssssssdsssssdddhhhx..OOOOOqq',
      '...........hhhssssssssssdsssssdddhhx....Oqqqq',
      '...........hhh.sssssBBBsdBBBssdd.hhx.....qqq',
      '............hh.sssssssssssskkddd.hh......oo',
      '............hhh.sssssssssskssdd.hhh.....oo',
      '.............hh.ssdkkkkkkwkwddd.hh......oo',
      '..............h..sssdssssssddd..h......oo',
      '...............h..sdsddsddddd..h.......oo',
      '...................sddddddddd.........oo',
      '...................sddddddddd.........oo',
      '..................hdddddddddd........oo',
      '..............hhhhhddddddddddhhhh....oo',
      '............hhhhhhhddddddddddhhhhhx.oo',
      '..........hhhhhhhhhhhhhhhhhhhhhhhxxxoo',
      '.........hhhhhhhhhhhhhhhhhhhhhhhxxxoox',
      '.......hhhhhhhhhhhhhhhhhhhhhhhhhxxxooxxx',
      '......hhhhhhhhhhhhhhhhhhhhhhhhhxxxooxxxxx',
      '.....hhhhhhhhhhhhhhhhhhhhhhhhhxxxxooxxxxxx',
      '.....hhhhhhhhhhhhhhhhhhhhhhhxsssssoxxxxxxx',
      '....hhhhhhhhhhhhhhhhhxxhxxxxxsdsssoxxxxxxxx',
      '...hhhhhhhhhhhhhhhhhxxxxxxxxxsssssxxxxxxxxxx',
      '...hhhhhhhhhhhhhhhhxxxxxxxxxxssssdxxxxxxxxxx',
      '...hhhhhhhhhhhhhhhxxxxxxxxxxxxxooxxxxxxxxxxx',
      '...hhhhhhhhhhhhhhxxxxxxxxxxxxxxooxxxxxxxxxxx',
      '...hhhhhhhhhhhhhxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    ],
    legend: {
      s: 'skin1',
      d: 'skin2',
      h: 'apron2',
      H: 'apron1',
      x: 'leather1',
      k: 'ink1',
      w: 'white1',
      B: 'hair3',
      o: 'oakbark2',
      O: 'oakbark1',
      q: 'oakbark3',
    },
    disc: ['red3', 'crimson2'],
  },
  // A smuggler: a knitted cap pulled low, a scowl under heavy brows, a black beard,
  // a gold ring in one ear, a striped shirt under a sea coat.
  smuggler: {
    rows: [
      '',
      '',
      '',
      '',
      '',
      '',
      '.......................r',
      '..................rrrrrrrrrrr',
      '................rrrrrrrrrrrrrrr',
      '..............rrrrrrrrrrrrrrrrrrr',
      '.............rrrrrrrrrrrrrrrrrrRRR',
      '.............rrrrrrrrrrrrrrrrrrRRR',
      '.............rrrrrrrrrrrrrrrrrrRRR',
      '.............rrrrrrrrrrrrrrrrrRRRRR',
      '.............rRrRrRrRrRrRrRrRRRRRRR',
      '.............RRRRRRRRRRRRRRRERRRRRR',
      '..............rrbbrrRRRRRRRRERbbR',
      '..............ssbbbbRRRRRRRRbEbbd',
      '..............ssssRbbbRRRRbbbEddd',
      '..............sssswkwssRssswkEddd',
      '.............ssssswkwsssssswkwEdd.d',
      '.............sssssssssssssssssEdd.g',
      '..............ssssssssssdsssssdddggg',
      '..............ssssssssssdsssssdddg.g',
      '..............bbbbbbbbbbbbbbbbbbb.g',
      '...............bbbbbbbbbbbbbbbbb',
      '...............bbbbssssssssssbbb',
      '................bbbbbbbbbbbbbbb',
      '................bbkbbbbbbbbbsbb',
      '.................bbkkkkkkkkkkb',
      '..................bbbbbbbbbbbk',
      '...................bbbbbbbbbb',
      '...................bbbbbbbbbb',
      '..................CbbbbbbbbbC',
      '...............CCCCdddddddddCCCC',
      '.............CCCCCCdddddddddCCCCCC',
      '............CCCCCCCcccccccccCCCCCCC',
      '............CCCCCCCcTTTTTTTTCCCCCCC',
      '...........CCCCCCCCCttttttttCCCCCCCC',
      '.........ccCCCCCCCCCTTTTTTTTCCCCCCCCcc',
      '........cccCCCCCCCCCttttttttCCCCCCCCccc',
      '......cccccCCCCCCCCCTTTTTTTTCCCCCCCCccccc',
      '.....ccccccCCCCCCCCCttttttttCCCCCCCCcccccc',
      '....ccccccCCCCCCCCCCTTTTTTTTCCCCCCCCCcccccc',
      '....ccccccCCCCCCCCccttttttttcCCCCCCCCcccccc',
      '...cccccccCCCcccccccTTTTTTTTccccccCCCccccccc',
      '...cccccccccccccccccttttttttcccccccccccccccc',
      '...cccccccccccccccccTTTTTTTTcccccccccccccccc',
    ],
    legend: {
      s: 'skingolden1',
      d: 'skingolden2',
      r: 'red2',
      R: 'red3',
      c: 'navy1',
      C: 'navy2',
      t: 'plaster1',
      T: 'red2',
      b: 'hairblack2',
      k: 'ink1',
      w: 'white1',
      g: 'gold1',
      E: 'lips1',
    },
    disc: ['wood4', 'wood3'],
  },
  // A marsh troll filling the frame: moss and reeds on its crown, small dull eyes
  // under a heavy brow, a bulbous nose, an underbite with two tusks.
  marsh_troll: {
    rows: [
      '',
      '',
      '',
      '.............M...M....M....M...M',
      '.............M...M....M....M...M',
      '.............M...M....M....M...M',
      '..............M...M...M.....M...M',
      '..............M...M....M....M...M',
      '..............M...M....M....M...M',
      '..............M...MmmmmMmmmmM...M',
      '................mmmmmmmmmmmmmmm',
      '............M.mmmmmmmmmmmmmmmmmmm..M',
      '.............ammmmmmmmmmmmmmmmmmmb',
      '...........aaaaaaammmmmmmmmmmbblbbbb',
      '..........aaaaaaaaaaaaaaaaaabbbbcbbbb',
      '.........aaaaaaaaaaaaaaaaaabbbbbbbbbbb',
      '.........aaaaaaaaaaaaaaaaaaaaaaaaaaabb',
      '........aaaccccccccccccccccccccccccccbb',
      '..a.....aaaccccccccccccccccccccccccccbb.....b',
      '..aa...aaaaaabccccbbbbbbbbbbbbccccbbbbbb...bb',
      '..aaa..aaaaabbykkybbbbbbbbbbbbykkybbbbbb..bbb',
      '..aaaa.aaaabbbykkybbbbbbbbbbbbykkybbbbbb.bbbc',
      '..aaaa.aaabbbbbbbbbbbbabbbbbbbbbbbbbbbbb.bbcc',
      '...aaaaaabbbbbbbbbbbaaaaabbbbbbbbbbbbbbbbbcc',
      '...aaaaaablbbbbbbbbaaaaaaabbbbbbbbbbbbbbcccc',
      '...aaaaabbbcbbbbbbbbaaaaabbbbbbbbbbbbbbccccc',
      '...aaaaabbbbbbbbbbbbbbaccccbbbbbbbbbbbcccccc',
      '.....aaabbbbbbbbbbbbcccccccccbbbbbbblbcccc',
      '.......abbbbbbbebbbbkkcccckkcbbbebbbbccc',
      '........bbbbbbeeebbbkkcccckkbbbeeebbbbc',
      '........bbbbbleeEbbbbbbbbbbbbbbeeEbbbbc',
      '.........bbbbbceEbbbbbbbbbbbbbbeeEbbbb',
      '.........bbbbbeeEbbbbbbbbbbbbbbeeEbbbb',
      '..........bbbbeeEbbbbbbbbbbbbbbeeEbbb',
      '...........kkkeeEkkkkkkkkkkkkkkeeEkkk',
      '............aaeeEaaaaaaaaaaaaaaeeEaa',
      '.............bbbbbbbbbbbbbbbbbbbbb',
      '..........bbbbbbbbbbbbbbbbbbbbbbbbbbc',
      '........bbbbbbbbbbbbbbbbbbbbbbbbbbbcccc',
      '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccc',
      '.....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccc',
      '....bbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccc',
      '...bbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccc',
      '..bbbbbbbbbbbbbbbbbbccccccccccccccccccccccccc',
      '.bbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccc',
      '.bbbbbbbbbbbbbbbbccccccccccccccccccccccccccccc',
      'bbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccc',
      'bbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccc',
    ],
    legend: {
      a: 'sage1',
      b: 'sage2',
      c: 'sage3',
      l: 'glowcap2',
      m: 'pine2',
      M: 'pine1',
      k: 'ink1',
      y: 'sand2',
      e: 'plaster1',
      E: 'plaster2',
    },
    disc: ['hide3', 'hide2'],
  },
  // The smith, as the town draws him: bald with a shine, a black beard, his apron's
  // bib over a grey shirt, one brow raised.
  smith: {
    rows: [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '.......................s',
      '....................sssssss',
      '..................ssSSsssssss',
      '.................ssSssssssssss',
      '................sssssssssssssss',
      '................sssssssssssssss',
      '...............sssssssssssssssss',
      '...............sssssssssssBBBBBs',
      '..............sssBBBBBsssBssssBdd',
      '..............ssssssssssssssssddd',
      '..............sssswkwsssssswkwddd',
      '.............ssssswkwsssssswkwddd.d',
      '.............sssssssssssssssssddd.d',
      '..............ssssssssssdsssssddd',
      '..............ssssssssssdsssssddd',
      '..............msssssssssdsssssddb',
      '..............mmssssssssdsssssdbb',
      '..............mmmssBBBBBBBBBsdbbb',
      '..............mmmmbBBBBBBBBBbbbbb',
      '..............mmmbbbbbbbbbbbbbbbb',
      '...............mmbbbbkkkkkkbbbbb',
      '...............mbbbbbbDDDDbbbbbB',
      '...............mbbbbbbbbbbbbbbBB',
      '...............mbbbbbbbbbbbbbbBB',
      '...............bbbbbbbbbbbbbbbBB',
      '...............bbbbbbbbbbbbbbBBB',
      '................bbbbbbbbbbbbbBB',
      '............AAA..GgbbbbbbbbbBg...AAA',
      '.............GAAggggggggggggggggAA',
      '..........GGgggAAAaaaaaaaaaaaaAAAgggg',
      '........GGGgggggaaaaaaaaaaaaaaagggggggg',
      '.......GGGggggggaaaaaaaaaaaaaaaggggggggg',
      '.....GGGGgggggggaaaaaaaaaaaaaaaggggggggggg',
      '....GGGGggggggggaaaaaaaaaaaaaaAgggggggggggx',
      '...GGGGgggggggggaaaaaaaaaaaaaAAggggggggggxxx',
      '..GGGGGgggggggggaaaaaaaaaaaaaAAggggggggxxxxxx',
      '..GGGGGgggggggggaaaaaaaaaaaaAAAggggggggxxxxxx',
      '.GGGGGGgggggggggaaaaaaaaaaaaAAAggggggggxxxxxxx',
      '.GGGGGGgggggggggaaaaaaaaaaAAAAAgggggggxxxxxxxx',
    ],
    legend: {
      s: 'skin1',
      d: 'skin2',
      S: 'white1',
      b: 'beard1',
      B: 'beard2',
      m: 'hair1',
      k: 'ink1',
      w: 'white1',
      D: 'lips2',
      g: 'stone2',
      G: 'stone1',
      x: 'stone3',
      a: 'apron1',
      A: 'apron2',
    },
    disc: ['red3', 'red2'],
  },
  // The trader: auburn hair to the shoulders, her linen apron over a purple dress, a
  // knowing smile.
  trader: {
    rows: [
      '',
      '',
      '',
      '',
      '',
      '.......................y',
      '...................yyyyyyyyy',
      '.................yyyyyyNyyyyyy',
      '................yyyyyyyNyyyyyhh',
      '...............yyyyyyyyyNyyyhhhh',
      '..............yyyyyyyyyyNyyhhhhhh',
      '.............yyyyyyyyyyyNyyhhhhhhh',
      '.............yyyyssssssssssssshhhh',
      '............yyyyssssssssssssssshhhh',
      '............yyyyssssssssssssssshhhh',
      '............yyyssssssssssssssssshhh',
      '............yyysssssssssssNNNssshhh',
      '............yyyssNNNNNsssssssNNddhh',
      '............yyysssssssssssssssdddhhN',
      '............yyyssswkwsssssswkwdddhNN',
      '............yyyssswkwsssssswkwdddNNN',
      '............yyysssssssssssssssdddNNN',
      '............yyysssssssssdsssssdddNNN',
      '............yyysssssssssdsssssdddNNN',
      '............yyysssssssssdsssssdddNNN',
      '............yyysssssssssdsssssddNNNN',
      '............yyhsssssDssssssDsdddNNNN',
      '............yhhhsssssDDDDDDssddNNNNN',
      '............hhhhssssssdssdssdddNNNNN',
      '............hhhhhssssssssssdddNNNNNN',
      '............hhhhh.sssddsddddd.NNNNNN',
      '............hhhhhh.sdddddddddNNNNNNN',
      '............hhhhhhhsdddddddddNNNNNNN',
      '............hhhhhhhddddddddddNNNNNNN',
      '............hhhhhhhddddddddddNNNNNNN',
      '............hhhhhhhddddddddddNNNNNNN',
      '............hhhhhhhddddddddddNNNNNNN',
      '............hhhhhhvvvvvvvvvvvNNNNNNN',
      '..............vvvvvvvvvvvvvvvvvvv',
      '............vvvvveeeeeeeeeeeeevvvvv',
      '..........vvvvvvveeeeeeeeeeeeevvvvvvv',
      '........vvvvvvvvveeeeeeeeeeeeevvvvvvvvv',
      '.......vvvvvvvvvveeeeeeeeeeeeevvvvvvvvvV',
      '......vvvvvvvvvvveeeeeeeeeeeeevvvvvvvVVVV',
      '.....vvvvvvvvvvvvveeeeeeeeeeevvvvvvvVVVVVV',
      '.....vvvvvvvvvvvvveeeeeeeeeeevvvvvvvvVVVVV',
      '....vvvvvvvvvvvvvveeeeeeeeeeevvvvvvvvVVVVVV',
      '....vvvvvvvvvvvvvveeeeeeeeeeevvvvvvvVVVVVVV',
    ],
    legend: {
      s: 'skin1',
      d: 'skin2',
      k: 'ink1',
      w: 'white1',
      D: 'lips2',
      h: 'auburn2',
      y: 'auburn1',
      N: 'auburn3',
      v: 'dress1',
      V: 'dress2',
      e: 'plaster1',
    },
    disc: ['pine3', 'pine2'],
  },
  // The pirate captain: a gold-trimmed tricorn, a patch over one eye and the other
  // looking straight out, a black beard, a grin with one gold tooth, red coat and
  // epaulettes.
  pirate: {
    rows: [
      '',
      '',
      '',
      '................zzzzzzzzzzzzzzz',
      '...............zzzzZZZZZZZZZZzzz',
      '..............zzzzzZZZZZZZZZZzzzz',
      '.............zzzzzzZZZZZZZZZZzzzzz',
      '............zzzzzzzZZZZZZZZZZzzzzzz',
      '..........zgzzzzzzzZZZZZZZZZZzzzzzzzg',
      '.........ggzzzzzzzzZZZZZZZZZZzzzzzzzzgg',
      '........gzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzg',
      '......ggzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzgg',
      '.....gzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz.g',
      '.....gggggggggggggggggggggggggggggggggggggg',
      '................sssssssssssssss',
      '..............kkssssssssssssssss',
      '...............skkkkksssssssssss',
      '..............sssbbbbbkksssssssdd',
      '..............sssssssssskkkkkkddd',
      '..............sssswkwssssskkkkddd',
      '.............ssssswkwssssskkkkddd.d',
      '.............ssssssssssssskkkkddd.d',
      '..............ssssssssssdsssssddd',
      '..............ssssssssssdsssssddd',
      '..............bsssssssssdsssssddb',
      '..............bbssssssssdsssssdbb',
      '..............bbbssbbbbbbbbbsdbbb',
      '...............bbbbbbbbbbbbbbbbb',
      '...............bbbbbbbbbbbbbbbbb',
      '...............bbbbbkkkkkkkkbbbb',
      '...............bbbbbkwwgwwwkbbbb',
      '...............bbbbbbbbbbbbbbbbb',
      '................bbbbbbbbbbbbbbb',
      '................bbbbbbbbbbbbbbb',
      '................bbbbbbbbbbbbbbb',
      '................bbbbbbbbbbbbbbb',
      '.................bbbbbbbbbbbbb',
      '....gggggg.......rrbbbbbbbbbrr.......gggggg',
      '..gggggggggg.rrrrrrbbbbbbbbbrrrrrr.gggggggggg',
      '.ggggggggggggrrrrrrbbbbbbbbbrrrrrrgggggggggggg',
      '.ggggggggggggrrrrrrebbbbbbberrrrrrgggggggggggg',
      '..ggggggggggrrrrrrgeeeeeeeeergrrrrrgggggggggg',
      '....ggggggrrrrrrrrreeeeeeeeerrrrrrrrrgggggg',
      '....rrrrrrrrrrrrrrrreeeeeeerrrrrrrrrrrrrrrr',
      '...rrrrrrrrrrrrrrrgreeeeeeerrgrrrrrrrrrrrRRR',
      '..rrrrrrrrrrrrrrrrrreeeeeeerrrrrrrrrrrrRRRRRR',
      '.rrrrrrrrrrrrrrrrrrreeeeeeerrrrrrrrrrrrRRRRRRR',
      '.rrrrrrrrrrrrrrrrrgreeeeeeerrgrrrrrrrrrRRRRRRR',
    ],
    legend: {
      s: 'skin1',
      d: 'skin2',
      k: 'ink1',
      w: 'white1',
      b: 'beard2',
      r: 'red2',
      R: 'red3',
      g: 'gold1',
      e: 'plaster1',
      z: 'navy2',
      Z: 'navy1',
    },
    disc: ['teal2', 'teal1'],
  },
};
