/**
 * Who you fight in a dungeon, drawn in the game's own hand: rows of
 * characters with a legend each, outlined automatically, facing right, lit
 * from the upper left. Creatures are their own drawings at whatever size suits
 * them; people are posed bodies of their own, arms doing something, what they
 * hold held by the hand rule (the grip through a fist, something of it above
 * and below), eyes mirrored. Size carries threat: the rat is small, a deckhand
 * the hero's height, the giant crab wide and low, the captain a head taller
 * than anyone.
 *
 * Each foe's `feet` is where it stands on the ground, counted on the drawing
 * before its outline; the outline adds a pixel all round, which `foeFigure`
 * accounts for.
 */
import { outline, parseSprite, type Grid, type Legend } from './grid';
import type { Glow } from './raster';

export interface FoeDef {
  readonly rows: readonly string[];
  readonly legend: Legend;
  /** Where it stands, on the drawing (before the outline). */
  readonly feet: readonly [x: number, y: number];
  /** Lights it carries (a lit fuse), on the drawing; they shine at dusk. */
  readonly glows?: readonly Glow[];
}

/* ----- Creatures ----- */

// A dock rat the size of a terrier, low and long, back up, sniffing the way
// ahead; a bald pink tail sweeping behind. The portrait's grey-brown fur.
const DOCK_RAT: FoeDef = {
  rows: [
    '........................ee....',
    '.......................eEEe...',
    '..............aaaaaa...eEEb...',
    '...........aaaaaaaaaaabeebbb..',
    '.........aaaaaaaaaaaaaabbbbbb.',
    '........baaaaaaaaaaaaaabbwkbbb',
    '.......bbaaaaaaaaaaaaabbbkkbbE',
    '.......bbbaaaaaaaaaabbbbbbbbbb',
    '......cbbbbbbbbbbbbbbbbbbbcwcc',
    '....EEcbbbbbbbbbbbbbbbbbcc.w..',
    '..EE..ccbbcc.....cbbcc.cc.....',
    '.E.....cc.cc......cc.cc.......',
    'E.............................',
  ],
  legend: {
    a: 'oakbark1',
    b: 'oakbark2',
    c: 'oakbark3',
    e: 'flush1',
    E: 'flush2',
    k: 'ink1',
    w: 'white1',
  },
  feet: [16, 11],
};

// A sand crab with opinions: square to you, the big claw up and open on the
// right, the other ready, eyes on stalks glaring, legs braced.
const SAND_CRAB: FoeDef = {
  rows: [
    '....................Rr',
    '.R.R................Rr...R',
    '.R.R......k....k...Rr...RZ',
    '.R.R......R....R...RrRRR.Z',
    '.RrRRR....R....R...RrrrRZ',
    '.RRRRR....R....R...RrrrRR',
    '.RRRRR....RRRRRR...RRRRRR',
    '...R.R..RrrrrrrRRR.RRRRR',
    '......RrrrrrrrrrrRRR',
    '......RrrrrrrrrrrRRR',
    '......RRRrrrrrrRRRRR',
    '......RRRRRRRRRRRRRR',
    '.....ZZZZZZZZZZZZZZZZ',
    '....Z...Z..RRRR..Z...Z',
    '....Z...Z.........Z...Z',
    '...Z...Z..........Z...Z',
  ],
  legend: {
    r: 'red1',
    R: 'red2',
    Z: 'red3',
    k: 'ink1',
  },
  feet: [12, 15],
};

// A crab the size of a rowing boat: wide and low under a crust of barnacles
// and weed, one great crushing claw raised and open, the other closed and
// ready. A brighter, older shell than the little red ones on the docks.
const GIANT_CRAB: FoeDef = {
  rows: [
    '...........................................OO',
    '........................................OOO',
    '...O....................................OoO',
    'Oo.O...............wkk......wkk........OoO.....oO',
    '.Oo.O..............kkk......kkk........OoO....oO.x',
    '.Oo.OO..............O........O........OoO....oO.x',
    '..OoooOO............O........O........OoOoOOoO.x',
    '..oooooOO...........O........O........oooooooOx',
    '.OOoooOOOO.........OOOOOOOOOOOO......OoooooooOOO',
    '..OOOOOOO......OoooooooooooooOOOOOO..OoooooooOOO',
    '...OOOOOO....ooooooooooooosSooooOOOOOOOOOoOOOOOO',
    '.....O.xxO..ooooosSooooooooosSoooOOOOOOOOOOOOOO',
    '.........xOoooooooooooooooooooooooOOOOOOOOOOOO',
    '..........OOooooooooooooooooooosSOOOOOOO',
    '..........OOOoooooooooooooooooooOOOOOOOO',
    '..........OOOOOOoooooooooooooOOOOOOOOOOO',
    '...........OOOOOOOOOOOOOOOOOOOOOOOOOOOO',
    '..........OxxxxxxxxxxxxoxxoxxxxxxxxxxxxO',
    '.......OxxxxxxgxxxxxxxgxxxxxxxxxxgxxxxxxxxO',
    '.....Oxx.....xgxxxxxxxgkkkkxxxxxxgxxx.....xxO',
    '.....Ox....Oxx.G.xxxxxxGxxxxxxxxx.G.xxO....xO',
    '....Ox...Oxx...Oxx..............xxO...xxO...xO',
    '....Ox...Ox...Ox..................xO...xO...xO',
    '...Ox...Ox....Ox..................xO....xO...xO',
    '...Ox...Ox....Ox...................xO...xO...xO',
    '..Ox...Ox....Ox....................xO....xO...xO',
    '..Ox...Ox....Ox....................xO....xO...xO',
  ],
  legend: {
    o: 'shrimp1',
    O: 'shrimp2',
    x: 'shrimp3',
    s: 'stone1',
    S: 'stone2',
    w: 'shell1',
    g: 'pine2',
    G: 'pine3',
    k: 'ink1',
  },
  feet: [24, 26],
};

// The ship's parrot, in the air and enjoying it: wings up, beak open, a red
// head over green, gold at the wing and blue in the tail. It flies at about
// a man's shoulder; its feet point is the ground below it.
const SHIPS_PARROT: FoeDef = {
  rows: [
    '...uU',
    '...uuU',
    '....uyU..........BB',
    '....uyyU........BBB',
    '.....uyrU......BBB',
    '.....uyrrU....BBB....rrr',
    '......uyrraA.BBB....rrrrr',
    '......uyrraAABB....rrWWrss',
    '.......uyraaAAB...rrrWkrsss',
    '........yraaaAA..rrrrrrkksS',
    '.........raaaaAArrrrrrrkktS',
    '..........aaaaaAArrrrr...tS',
    '.........AaaaaaaAArrr.....t',
    '........AAaaaaaaaAA',
    '.......rAAAaaaaaAA',
    '......rUAAAAAAAAA',
    '.....rUuAAAAAA.t.t',
    '....rUuu......t.t',
    '...rUuu',
    '..rUuu',
    '.rUuu',
    '.Uuu',
    'Uu',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
  legend: {
    a: 'grass1',
    A: 'grass2',
    B: 'grass3',
    r: 'red1',
    y: 'gold1',
    u: 'blue1',
    U: 'blue2',
    k: 'ink1',
    W: 'white1',
    s: 'stone1',
    S: 'stone2',
    t: 'stone3',
  },
  feet: [13, 36],
};

/* ----- People ----- */

// A deckhand: red bandana knotted at the side, stubble, a striped jersey and
// a sash, canvas trousers rolled to the shin, bare feet. One hand on his hip,
// the other closed on a boathook taller than he is: spike up, hook out.
const DECKHAND: FoeDef = {
  rows: [
    '.................rrrrrrRR......M',
    '...............rrrrrrrrrRRR....Mq',
    '..............rrrrrrrrrrrRRZ...Mq',
    '..............rRRRRRRRRRRRZZZ..MqMm',
    '...............dsssssssssdZRZ..Mq..m',
    '...............dsHHssssHHdd.RZ.Mq..mq',
    '...............dswksssskwdd..Z.Mq..q',
    '................sssssssssd.....Mq.qq',
    '................sssbddbssdd....qq',
    '................sbsDDDDsbdd....qq',
    '.................sbbbbbbd......jo',
    '..................sbbbbd.......jo',
    '...................dddd........jo',
    '...................sddd........jo',
    '..............eeeeeessddeeeE...jo',
    '.........eeeEeeeeeeeeeeeeeEeEEEjo',
    '........nnnnNnnnnnnnnnnnnnNNNNjo',
    '........eeeeEeeeeeeeeeeeeeEEEEjo',
    '.......nnnnNnnnnnnnnnnnnnnNNNNjo',
    '.......sssdeeeeeeeeeeeeeeeEEsdjo',
    '.......sssdnnnnnnnnnnnnnnnNNsdjo',
    '.......ssd.eeeeeeeeeeeeeeeEEsdjo',
    '.......sssdnnnnnnnnnnnnnnnNNsdjo',
    '........sssdeeeeeeeeeeeeeEEEsdjo',
    '.........sssddnnnnnnnnnnnNNNsdjo',
    '..........sssddeeeeeeeeeEEE.sdjo',
    '...........ssddrrrrrrrrrRRR.sssd',
    '.............rrRRrrrrrrrRRZ.ssdd',
    '..............rrZRZ..........ddd',
    '...............RZRZ..........jo',
    '...............ZR.Z..........jo',
    '..............llllllLLLLLL...jo',
    '..............llllllLLLLLL...jo',
    '..............lllllLL.LLLL...jo',
    '.............llllllL..LLLLL..jo',
    '.............llllllL..LLLLL..jo',
    '.............lllllL...LLLLL..jo',
    '.............lllllL...LLLLL..jo',
    '.............llllLL....LLLLL.jo',
    '.............IIIIII....IIIII.jo',
    '..............ssdd.....sddd.jo',
    '..............ssdd.....sddd.jo',
    '..............ssdd.....sddd.jo',
    '..............ssdd.....sddd.jo',
    '.............sssdd.....sddddjo',
    '.............ssdddd....sddddjo',
    '.............ddddd.....dddddjo',
  ],
  legend: {
    D: 'lips2',
    E: 'plaster2',
    H: 'hair3',
    I: 'linen3',
    L: 'linen2',
    M: 'metal1',
    N: 'navy2',
    R: 'red2',
    Z: 'red3',
    b: 'beard1',
    d: 'skin2',
    e: 'plaster1',
    j: 'wood1',
    k: 'ink1',
    l: 'linen1',
    m: 'metal2',
    n: 'navy1',
    o: 'wood3',
    q: 'metal3',
    r: 'red1',
    s: 'skin1',
    w: 'white1',
  },
  feet: [21, 46],
};

// The Saltmarsh smuggler, as his portrait has him: a red knitted cap, a black
// beard, a gold ring in one ear, a striped shirt under a long sea coat. A
// cutlass up in one fist (iron, brass guard and knuckle bow) and in the other
// hand a corked bottle, which is what he throws.
const SMUGGLER: FoeDef = {
  rows: [
    '...................rrrrr',
    '.................rrrrrrrrR',
    '................rrrrrrrrrRR',
    '................rrrrrrrrrRRR',
    '...............RRRRRRRRRRRRRZ......MM',
    '...............ZRZRZRZRZRZRZZ.....MMm',
    '................cKKccccKKcCC.....MMm',
    '...............gcwkcccckwcCC.....MMm',
    '................ccccccccccC.....MMm',
    '................ccccCCcccCC.....MMm',
    '................cBBByyyyBBBC...MMm',
    '................BBBBBBBBBBBB...MMm',
    '.................BBBBBBBBBB....MMm',
    '..................BBBBBBBB....MMm',
    '.............nnnnccCBBBBN.....MMm',
    '.........nnnnnnnnrcCCrnnNN.NNNMMm',
    '........nnnNnnnn%rrrr%nnNNNNNNMMm',
    '........nnnNnnnnr%%%%rnnNNN.NNMMm',
    '.......nnnNnnnnn%rrrr%nnNNN.NNMMm',
    '.......nnnNnnnnnr%%%%rnnNNN.NNMMm',
    '.......nnnNnnnnn%rrrr%nnNNN.NNMMm',
    '......nnnN.nnnnnr%%%%rnnNNN.NNMMm',
    '......nnnN.nnnnn%rrrr%nnNNN..GgggG',
    '......nnNoonnnnnr%%%%rnnNNN..GNNNG',
    '......ccTTFnnnnn%rrrr%nnNNN..cccCG',
    '......cTttTFnnnnfffgffnnNNN..ccCC',
    '.......TtTTFnnnnr%%%%rnnNNN..cCCC',
    '.......TtTTFnnnnNNNNNNnnNNN..GCCC',
    '......cccCTFnnnnNNNNNNnnNNN...GG',
    '......cCCCTFnnnnNN.NNNNnNNN',
    '.......TTTFnnnnnNN.NNNnnNNNN',
    '..........nnnnnnNN..NNnnNNNN',
    '..........nnnnnnnN..NnnnNNNN',
    '.........nnnnnnnnNNNNnnnNNNNN',
    '.........nnnnnnnNNNN.nnnnNNNN',
    '.........nnnnnnNNNNN..nnnNNNN',
    '.........NNNNNNNNNNN...NNNNNN',
    '...............NNNNN...NNNNN',
    '...............ffffx...ffffx',
    '...............ffffx...ffffx',
    '...............ffffx...ffffx',
    '...............ffffx...ffffx',
    '...............ffffx...ffffx',
    '..............fffffx...fffffx',
    '..............xxxxxx...xxxxxx',
  ],
  legend: {
    '%': 'shell1',
    B: 'beard2',
    C: 'skinbrown2',
    F: 'pine3',
    G: 'gold2',
    K: 'hairblack1',
    M: 'metal1',
    N: 'navy2',
    R: 'red2',
    T: 'pine2',
    Z: 'red3',
    c: 'skinbrown1',
    f: 'leather1',
    g: 'gold1',
    k: 'ink1',
    m: 'metal2',
    n: 'navy1',
    o: 'wood3',
    r: 'red1',
    t: 'pine1',
    w: 'white1',
    x: 'shade1',
    y: 'skinbrown3',
  },
  feet: [22, 44],
};

// The powder monkey: a small, wiry grown man, bald and sooty, stubbled, eyes
// wide and grinning with every tooth. A keg held up high with its fuse lit,
// coils of fuse in the other arm, a leather vest, bare feet.
const POWDER_MONKEY: FoeDef = {
  rows: [
    '................................',
    '',
    '',
    '',
    '',
    '.....................4',
    '....................454',
    '.....................5',
    '....................o',
    '..................WjjWo',
    '.................qqqqqq',
    '.................jWWWWo',
    '.................jWWWWo',
    '.................qqqqqq',
    '..................jWWo',
    '...........sssss.....sssd',
    '..........sxssssd.....ssd',
    '.........hsssssxdh....ssd',
    '.........HHssssHHd....ssd',
    '........dwkssssskwd...ssd',
    '.........ssssssssd...sdd',
    '.........sssssddsd..ssd',
    '.........bDwwwwwDb.sssd',
    '..........bDwwwDb.sssdd',
    '...........bbbbb..ssdd',
    '............ddd...8sdd',
    '........77sssssss98',
    '....lLlL77sssssss998',
    '...lLx.lL7ssssss9988',
    '..lL.lLlL7sssssd9988',
    '..lLlL.lL7sssssd9988',
    '...lLsssL7sssssd998',
    '....sssdLxIIIIIIIII',
    '.....ldLllllllLLLL',
    '......lLxllll.LLLL',
    '........lllll.LLLL',
    '........LLLLL.LLLL',
    '.........sdd...sdd',
    '.........sdd...sdd',
    '.........sdd...sdd',
    '........sssd..sssd',
    '........dddd..dddd',
  ],
  legend: {
    '4': 'fire1',
    '5': 'fire2',
    '7': 'tan1',
    '8': 'tan2',
    '9': 'tan3',
    D: 'lips2',
    H: 'hair3',
    I: 'linen3',
    L: 'linen2',
    W: 'wood2',
    b: 'beard1',
    d: 'skin2',
    h: 'hair2',
    j: 'wood1',
    k: 'ink1',
    l: 'linen1',
    o: 'wood3',
    q: 'metal3',
    s: 'skin1',
    w: 'white1',
    x: 'shade1',
  },
  feet: [13, 41],
  glows: [{ x: 21, y: 6, radius: 7, strength: 0.6 }],
};

// Captain Brinebeard: a head taller and twice as broad as anyone. A great
// black tricorn with a skull on it, brows down over a broad red face, a gold
// tooth, a beard grey-green with brine in two forked braids hung with shells
// and weed; a purple coat trimmed in gold over a red sash. One fist on his
// hip, the other round the shank of his own anchor, which stands on its crown
// beside him as tall as his shoulder: ring, wooden stock, and two curved arms.
// Not the town's captain: no patch, no peg, no red coat.
const BRINEBEARD: FoeDef = {
  rows: [
    '....................JJJJJJJJJJ',
    '.................JJJJJJJJJJJJJJJJ',
    '..........Y....JJJJJJJJwwwJJJJJJJJJ....Y',
    '..........YJ..JJJJJJJJJwkwJJJJJJJJJJ..JY',
    '..........YJJJJJJJJJJJJJwJJJJJJJJJJJJJJY',
    '..........gYJJJJJJJJJJJJJJJJJJJJJJJJJJYg',
    '...........gggYYYYYYYYYYYYYYYYYYYYYYggg',
    '..............gggggggggggggggggggggg',
    '.................gggggggggggggggg',
    '...................pppppppppppppP',
    '..................ppppppppppppppPP',
    '..................pKKKKppppppKKKKP',
    '..................ppKKKKppppKKKKPP',
    '..................ppwkkpppppkkwpPP',
    '..................pppppppPPpppppPP',
    '..................pAaaaPPPPPPaAAA',
    '.................aaaaaaaaaaaaaaAAAAA',
    '................aaVaaaaQwgwQaaAAVAAA',
    '...............aaaVaaaaQQQQQaaAAAVAAA',
    '...............aaaaVaaaaaaaaaaAAVAAAA........Mmmq',
    '..............aaVaaaVaaaaaaaAAVAAAVAAA......M....q',
    '..............aaaVaaaTaaaaVAAAAVAAAVAAUUUUU.m....q',
    '..........uuuu.aaaVaaaaaVaaAAAVAAAAAA.UUUUUU.mqqq',
    '.........uuuuuuuaaaVaaaaVaAAAVAAAAAAUUjjjjjjjMMmqjjjjjjjo',
    '........uuuuuXuuuaaaVaaaVaAAVAAAAAAUUUoooooooMMmqoooooooO',
    '.......uuuuuXuuuuuaaaVaaVuuAVAAAAUUUUUU.UUUUGpppP',
    '......uuuuuXuuuuuuuaaVa%uuuUAVA%UUUUUUU......ppPP',
    '.....uuuuuXuuuuuuuuaaVa%uuuUAVAUUUUUUUU......MPPP',
    '.....uuuuX.uuuuuuuuuaaa%uuuUUAA%UUUUUUU......MMmq',
    '......uuuuXuuuuuuuuu%ua%uugUUAVUUUUUUUU......MMmq',
    '.......uuuuXuuuuuuuuuu%uuuuUUU%UUUUUUUU......MMvq',
    '........gggGuuuuuuuuuuuuuUUUUUUUUUUUUUU......MMmq',
    '.........pppPuuuuuuuuuuugUgUUUUUUUUUUUU......MMmq',
    '..........ppPPrrrrrrrrrrrrRRRRRRRRRRRRR......MMmq',
    '...........RRRRRRRRRRRggggGRRRRRRRRRRRR......MMmq',
    '...........rrrrrrrrrrrgfffGRRRRRRRRRRRR......MMmq',
    '...........uuuuuuuuuuuggggGUUUUUUUUUUUU......MMmq',
    '...........uuuuuuuuuuuuuuUUUUUUUUUUUUUU......MMmq',
    '...........uuuuuuuuuuuuuuXUUUUUUUUUUUUU......MMmq',
    '...........uuuuuuuuuuuuuuXUUUUUUUUUUUUU......MMvq',
    '..........uuuuuuuuuuuuuuuXUUUUUUUUUUUUUU.....MMmq',
    '..........uuuuuuuuuuuuuuuXUUUUUUUUUUUUUU.....MMmq',
    '..........uuuuuuuuuuuuuu...UUUUUUUUUUUUU.....MMmq',
    '..........uuuuuuuuuuuuu.....UUUUUUUUUUUUU....MMmq',
    '..........uuuuuuuuuuuu.......UUUUUUUUUUUU....MMmq',
    '..........uuuuuuuuuuu.........UUUUUUUUUUU....MMmq',
    '..........ggggggggggNNNN.......GGGGGGGGGG....MMmq',
    '...................NNNNN.......NNNNN.........MMmq',
    '..................fffffff.....fffffff........MMmq',
    '..................fffffff.....fffffff........MMmq',
    '..................fffffff.....fffffff........MMmq',
    '..................fffffff.....fffffffMM......MMmq......mqq',
    '..................fffffff.....fffffffMMm.....MMmq.....mmqq',
    '..................fffffff.....fffffffMMMm....MMmq....mmqq',
    '..................fffffff.....fffffff.MMmq...MMmq...Mmqq',
    '..................ffgffff.....ffffgff..MMmq..MMmq..MMmq',
    '.................ffffffffx...ffffffffx..MMmqqMMmqqMMmq',
    '.................ffffffffx...ffffffffx...MMmmMMmqmmmq',
    '.................fffffffffx..fffffffffx...MMMmmmmqqq',
    '.................xxxxxxxxxx..xxxxxxxxxx.....MMmmqqq',
  ],
  legend: {
    '%': 'shell1',
    A: 'sage2',
    G: 'gold2',
    J: 'hairblack2',
    K: 'hairblack1',
    M: 'metal2',
    N: 'navy2',
    O: 'wood4',
    P: 'skinpale2',
    Q: 'skinpale3',
    R: 'red2',
    T: 'pine2',
    U: 'midnight2',
    V: 'sage3',
    X: 'midnight3',
    Y: 'hairblack3',
    a: 'sage1',
    f: 'leather1',
    g: 'gold1',
    j: 'wood1',
    k: 'ink1',
    m: 'metal3',
    o: 'wood3',
    p: 'skinpale1',
    q: 'slate3',
    r: 'red1',
    u: 'midnight1',
    v: 'rust2',
    w: 'white1',
    x: 'shade1',
  },
  feet: [28, 59],
};
export const FOES: Readonly<Record<string, FoeDef>> = {
  dock_rat: DOCK_RAT,
  sand_crab: SAND_CRAB,
  giant_crab: GIANT_CRAB,
  ships_parrot: SHIPS_PARROT,
  smuggler: SMUGGLER,
  deckhand: DECKHAND,
  powder_monkey: POWDER_MONKEY,
  brinebeard: BRINEBEARD,
};

export const FOE_IDS: readonly string[] = Object.keys(FOES);

/** A foe's drawing, outlined, and its feet on the outlined picture. */
export function foeGrid(def: FoeDef): {
  grid: Grid;
  feet: { x: number; y: number };
  glows: Glow[];
} {
  const g = outline(parseSprite(def.rows, def.legend));
  const glows = (def.glows ?? []).map((l) => ({ ...l, x: l.x + 1.5, y: l.y + 1.5 }));
  return { grid: g, feet: { x: def.feet[0] + 1, y: def.feet[1] + 1 }, glows };
}
