/**
 * Skill icons: one clear object for each skill, drawn by hand as rows of
 * characters like the item icons, and lit from the upper left. Ids are the
 * game's skill ids, kept here as plain strings.
 */
import type { Legend } from './grid';
import type { IconDef } from './iconKit';

/** Steel, wood and leather, shared by the tools. */
const TOOLS: Legend = {
  M: 'metal1',
  m: 'metal2',
  n: 'metal3',
  q: 'slate3',
  j: 'wood1',
  W: 'wood2',
  o: 'wood3',
  O: 'wood4',
  f: 'leather1',
  g: 'gold1',
  G: 'gold2',
};

const WOODCUTTING: readonly string[] = [
  '..................Wo',
  '.................Wo',
  '................Wo',
  '...............Wo',
  '..............Wo',
  '.............Wo',
  '............Wo',
  '...........Wo',
  '.......Mm.Wo',
  '......MMmWo',
  '.....MMmmnn',
  '....aMmmnnaaaaaa',
  '..aaeeMmneeeeeeeaab',
  '.aeeeefffffffffeeeb',
  'aeeeefeeeeggeeefeeb',
  'aeeeeefffffffffeebc',
  'baeeeeeeeeeeeeeebcc',
  'babbbbbbbbbbbbbbbcc',
  'aabbcbbbbbbcbbbbccc',
  'aabbcbbbbbbcbbbbccc',
  'aaabbbbbbbbbbbbbccc',
  'aab..bbbccbb..bbcc',
];

const FISHING: readonly string[] = [
  '.l',
  '.l',
  '.l',
  '.l',
  '.l',
  '.l',
  '.l',
  '.l',
  '.l',
  '.l',
  '.l',
  '.l',
  '.M',
  '.M...ccccccc.......cc',
  '.M.ccdddddddcc....cdd',
  'M.cdddddddddddddc.cdd',
  '.cwkddgdddddddddddcd.',
  'cdbbbbgbbbbbbbbbbbd..',
  '.aaaaagaaaaaaaaaabgg.',
  '..aaagaaaaaaaaab..ggg',
  '...bbaaaaaaabb....bgg',
  '.....bbbbbbb.......gg',
];

const MINING: readonly string[] = [
  '......nmmmmmmmn',
  '....mMMMMMMMMMMmn',
  '...MMmmmnWonnmmmMn',
  '..Mmn....Wo....nnMm',
  '..Mn.....Wo......nM',
  '..M......Wo.......n',
  '.........Wo',
  '.........Wo',
  '.........Wo',
  '.........Wo',
  '.........Wo',
  '.........Wo',
  '.........Wo',
  '.........Wo',
  '.........Wo',
  '.........Wo',
  '.........Wo',
  '.........Wo',
  '.........Wo',
  '.........Wo',
  '.........oO',
];

const FORAGING: readonly string[] = [
  '........aab',
  '..ss...aabbc....gg',
  '.sSs..aabbbc...gGGg',
  '.sSSs.abbbcc..gGGGg',
  '..sSssbbccc.ssgGGg',
  '..sSSsss.e..sSSdGd',
  '...ssSSsee.sSSs.dd',
  'FjjjjjjjjjjjjjjjjjX',
  'FjWjWjWjWjWjWjWjWjX',
  '.FWjWjWjWjWjWjWjWX#',
  '.FjWjWjWjWjWjWjWjX#',
  '.FWjWjWjWjWjWjWjWX#',
  '..FjWjWjWjWjWjWjX#',
  '..FWjWjWjWjWjWjWX#',
  '...FXXXXXXXXXXXX#',
  '....############',
];

const COOKING: readonly string[] = [
  '......w...w',
  '.....w...w...w',
  '......w...w.w',
  '.....w...w...w',
  '..',
  '.nnnnnnnnnnnnnnnn',
  'nMmmmmmmmmmmmmmnnn',
  'nmMmmmmmmmmmmmmnnq',
  '.nMmmmmmmmmmmmnnq',
  '.nmmmmmmmmmmmmnnq',
  '..nmmmmmmmmmmnnq',
  '...nnnnnnnnnnnq',
  '....f..ff..f',
  '...fFf.fFf.fF',
  '..fFrFffFrFfFrf',
  '..fFrrFFrrFFrrF',
  '.ooooooooooooooo',
  '..OOOOOOOOOOOOO',
];

const SMITHING: readonly string[] = [
  '........WWo',
  '.......WWo',
  '.....MmmnWo',
  '....MMmmnnWo',
  '.....mmnn..Wo',
  '.............Wo',
  '..............Wo',
  'MMMMMMMMMmmmmmmnn',
  'mmmmmmmmmmmmmmnnn',
  '.nnnmmmmmmmmnnnnn',
  '.....nmmmmmnnnn..',
  '......nmmmnnn',
  '......nmmmnnn',
  '.....nmmmmnnnn',
  '....nnnnnnnnnnnn',
  '...ooooooooooooooo',
  '...oOOOOOOOOOOOOOo',
  '...OOOOOOOOOOOOOOO',
];

const CRAFTING: readonly string[] = [
  '...............M',
  '..............Mn',
  '.............Mn',
  '............Mn',
  '...........Mn',
  '..........Mn',
  '.....oooooMoo',
  '.....OOOOMOOO',
  '......rrMrrrR',
  '......rMrrrrR',
  '......Mrrrrr',
  '.....MnrrrrR',
  '....MnRrrrrR',
  '...Mn.rrrrrR',
  '..Mn..rrrrrR',
  '.Mn..ooooooo',
  '.n...OOOOOOO',
];

const FLETCHING: readonly string[] = [
  '..................e',
  '................eeE',
  '...............eeEE',
  '..............eeeE',
  '............eeeEE',
  '...........eeEEE',
  '..........eeeEE',
  '.........eeEEE',
  '........eeeEE',
  '.......eeEEE',
  '......eeeEE',
  '.....eeEE.',
  '....eEE',
  '...EEW',
  '..E.W',
  '...W',
  '..W',
  '.W',
];

const ALCHEMY: readonly string[] = [
  '..............jW',
  '.............jWo',
  '............jWo',
  '...ab......jWo',
  '..aabc....jWo',
  '..abbc...jWo',
  '...bc...jWo',
  '.......jWo',
  'aaaaaaaaaaaaaaaaab',
  'aCCCCCCCCCCCCCCCbb',
  '.abbbbbbbbbbbbbbc',
  '.abbbbbbbbbbbbbbc',
  '..abbbbbbbbbbbbc',
  '...abbbbbbbbbbc',
  '....acccccccccc',
  '.....abbbbbbc',
  '....aacccccccc',
];

const MELEE: readonly string[] = [
  '.M..................n',
  '.Mmn..............Mmn',
  '..Mmn............Mmn',
  '...Mmn..........Mmn',
  '....Mmn........Mmn',
  '.....Mmn......Mmn',
  '......Mmn....Mmn',
  '.......Mmn..Mmn',
  '........MmnMmn',
  '.........MMmn',
  '......G..Mmnn..g',
  '.......GMmnMmng',
  '........G....g',
  '.......f.G..g.f',
  '......fO..Gg..Of',
  '.....fO........Of',
  '...gGO..........OgG',
  '...GG............GG',
];

const RANGED: readonly string[] = [
  '.....aab',
  '...aab..e',
  '..ab.....e',
  '.ab.......e',
  '.ab........e',
  'ab..........e',
  'ab...........e',
  'ab............e',
  'FX.............e',
  'FXSSSSSSSSSSSSSSs12',
  'FX.............e',
  'ab............e',
  'ab...........e',
  'ab..........e',
  '.ab........e',
  '.ab.......e',
  '..ab.....e',
  '...aab..e',
  '.....aab',
];

const DEFENCE: readonly string[] = [
  'nnnnnnnnnnnnnnnn',
  'nMMMMMMMMMMMMMMn',
  'nMuuuuuuuuuuuuUn',
  'nMuuuuuuuuuuuUUn',
  'nMuuuuuuuuuuuUUn',
  'nMuuuuuMmnuuuUUn',
  'nMuuuuMmmnnuuUUn',
  'nMuuuuMmnnnuuUUn',
  'nMuuuuunnnuuuUUn',
  '.nMuuuuuuuuuUUn',
  '.nMuuuuuuuuuUUn',
  '..nMuuuuuuuUUn',
  '...nMuuuuuUUn',
  '....nMuuuUUn',
  '.....nMuUUn',
  '......nMUn',
  '.......nn',
];

const VITALITY: readonly string[] = [
  '..rrrrr....rrrrr',
  '.rwwrrrr..rrrrrRR',
  'rrwwrrrrrrrrrrrRRR',
  'rrwrrrrrrrrrrrrRRR',
  'rrrrrrrrrrrrrrrRRR',
  'rrrrrrrrrrrrrrRRRR',
  '.rrrrrrrrrrrrrRRR',
  '..rrrrrrrrrrrRRR',
  '...rrrrrrrrrRRR',
  '....rrrrrrrRRR',
  '.....rrrrrRRR',
  '......rrrRRR',
  '.......rRRR',
  '........RR',
];

// Thieving: a fat purse with its string cut, a coin dropping out of it.
const THIEVING: readonly string[] = [
  '.......l....L',
  '........l..L',
  '.........lL',
  '........bccb',
  '.......abbbbc',
  '......aayyYbbc',
  '.....aayYYYybbc',
  '....aaaaaaaabbbc',
  '...aaaaaaaabbbbbc',
  '...aaaaaaaaabbbbc',
  '..aaaaaaaaabbbbbbc',
  '..aaaaaaaaabbbbbbc',
  '..aaaaaaaabbbbbbbc',
  '...aaaaaabbbbbbbc',
  '...aaaabbbbbbbbcc',
  '....bbbbbbbbbccc',
  '......ccccccc',
  '...................yy',
  '..................yYYy',
  '..................yYYY',
  '...................YY',
];

export const SKILL_ICON_DEFS: Readonly<Record<string, IconDef>> = {
  woodcutting: {
    rows: WOODCUTTING,
    legend: {
      ...TOOLS,
      a: 'wood2',
      b: 'wood3',
      c: 'wood4',
      e: 'pinewood1',
      f: 'pinewood2',
      g: 'wood3',
    },
  },
  fishing: {
    rows: FISHING,
    legend: {
      ...TOOLS,
      l: 'plaster2',
      a: 'scales1',
      b: 'scales2',
      g: 'scales3',
      c: 'herring1',
      d: 'herring2',
      w: 'white1',
      k: 'ink1',
    },
  },
  mining: { rows: MINING, legend: TOOLS },
  foraging: {
    rows: FORAGING,
    legend: {
      ...TOOLS,
      a: 'glowcap1',
      b: 'glowcap2',
      c: 'glowcap3',
      e: 'plaster1',
      s: 'sage1',
      S: 'sage2',
      g: 'grass1',
      G: 'grass2',
      d: 'plaster2',
      F: 'wood1',
      X: 'wood3',
      '#': 'wood4',
    },
  },
  cooking: {
    rows: COOKING,
    legend: { ...TOOLS, w: 'smoke1', f: 'fire1', F: 'fire2', r: 'fire3' },
  },
  smithing: { rows: SMITHING, legend: TOOLS },
  crafting: { rows: CRAFTING, legend: { ...TOOLS, r: 'crimson1', R: 'crimson2' } },
  fletching: { rows: FLETCHING, legend: { ...TOOLS, e: 'white1', E: 'plaster2' } },
  alchemy: {
    rows: ALCHEMY,
    legend: { ...TOOLS, a: 'stone1', b: 'stone2', c: 'stone3', C: 'tonic2' },
  },
  melee: { rows: MELEE, legend: TOOLS },
  ranged: {
    rows: RANGED,
    legend: {
      ...TOOLS,
      a: 'wood1',
      b: 'wood3',
      e: 'plaster1',
      F: 'hide1',
      X: 'hide2',
      S: 'pinewood1',
      s: 'pinewood2',
      '1': 'metal1',
      '2': 'metal3',
    },
  },
  defence: { rows: DEFENCE, legend: { ...TOOLS, u: 'crimson1', U: 'crimson2' } },
  vitality: { rows: VITALITY, legend: { r: 'red1', R: 'red2', w: 'flush1' } },
  thieving: {
    rows: THIEVING,
    legend: { a: 'tan1', b: 'tan2', c: 'tan3', y: 'gold1', Y: 'gold2', l: 'linen1', L: 'linen2' },
  },
};
