/**
 * Every C-scale town piece's facts (size, base line, layer, foot, spots,
 * shadow, ground, what goes with it), written down so the layout needs no
 * drawing (`town2Facts` in pieces.ts). Generated from the drawn pieces;
 * tests/art/town2.test.ts holds that they still match them.
 */
import type { Town2Facts, Town2Id } from './pieces';

export const FACTS_TABLE: Readonly<Record<Town2Id, Town2Facts>> = {
  tavern: {
    id: 'tavern',
    w: 593,
    h: 412,
    base: 405,
    layer: 'stand',
    foot: 267,
    spots: { door: { x: 267, y: 407 } },
    shadow: { kind: 'wall', x0: 25, x1: 508, height: 405 },
    ground: { w: 483, d: 137 },
    attached: [{ id: 'tavern_smoke', x: 360, y: -54 }],
  },
  smithy: {
    id: 'smithy',
    w: 485,
    h: 301,
    base: 294,
    layer: 'stand',
    foot: 210,
    spots: { door: { x: 311, y: 296 }, forge: { x: 177, y: 296 } },
    shadow: { kind: 'wall', x0: 3, x1: 417, height: 294 },
    ground: { w: 414, d: 137 },
    attached: [{ id: 'smithy_smoke', x: 115, y: -54 }],
  },
  house: {
    id: 'house',
    w: 358,
    h: 286,
    base: 279,
    layer: 'stand',
    foot: 178,
    spots: { door: { x: 163, y: 281 } },
    shadow: { kind: 'wall', x0: 22, x1: 334, height: 279 },
    ground: { w: 312, d: 137 },
    attached: [{ id: 'tavern_smoke', x: 279, y: -54 }],
  },
  stall: {
    id: 'stall',
    w: 131,
    h: 112,
    base: 110,
    layer: 'stand',
    foot: 66,
    spots: { counter: { x: 66, y: 114 } },
    shadow: { kind: 'oval', cx: 66, rx: 68, ry: 21.76 },
    ground: { w: 122, d: 30 },
    attached: [],
  },
  pier: {
    id: 'pier',
    w: 111,
    h: 490,
    base: 488,
    layer: 'ground',
    foot: 56,
    spots: {},
    shadow: { kind: 'water', x0: 4, x1: 107 },
    ground: { w: 0, d: 0 },
    attached: [],
  },
  ship: {
    id: 'ship',
    w: 542,
    h: 496,
    base: 492,
    layer: 'stand',
    foot: 271,
    spots: {},
    shadow: { kind: 'water', x0: 160, x1: 508 },
    ground: { w: 0, d: 0 },
    attached: [],
  },
  well: {
    id: 'well',
    w: 70,
    h: 101,
    base: 96,
    layer: 'stand',
    foot: 35,
    spots: {},
    shadow: { kind: 'oval', cx: 35, rx: 38, ry: 12.16 },
    ground: { w: 61, d: 30 },
    attached: [],
  },
  notice_board: {
    id: 'notice_board',
    w: 67,
    h: 86,
    base: 84,
    layer: 'stand',
    foot: 34,
    spots: {},
    shadow: { kind: 'oval', cx: 34, rx: 34, ry: 10.88 },
    ground: { w: 57, d: 30 },
    attached: [],
  },
  signpost: {
    id: 'signpost',
    w: 78,
    h: 97,
    base: 95,
    layer: 'stand',
    foot: 39,
    spots: {},
    shadow: { kind: 'oval', cx: 39, rx: 15, ry: 4.8 },
    ground: { w: 19, d: 19 },
    attached: [],
  },
  anvil: {
    id: 'anvil',
    w: 40,
    h: 38,
    base: 36,
    layer: 'stand',
    foot: 20,
    spots: {},
    shadow: { kind: 'oval', cx: 20, rx: 21, ry: 6.72 },
    ground: { w: 30, d: 30 },
    attached: [],
  },
  lamp: {
    id: 'lamp',
    w: 25,
    h: 122,
    base: 118,
    layer: 'stand',
    foot: 13,
    spots: {},
    shadow: { kind: 'oval', cx: 13, rx: 13, ry: 4.16 },
    ground: { w: 19, d: 19 },
    attached: [],
  },
  barrel: {
    id: 'barrel',
    w: 28,
    h: 43,
    base: 40,
    layer: 'stand',
    foot: 14,
    spots: {},
    shadow: { kind: 'oval', cx: 14, rx: 15, ry: 4.8 },
    ground: { w: 23, d: 23 },
    attached: [],
  },
  crate: {
    id: 'crate',
    w: 29,
    h: 37,
    base: 35,
    layer: 'stand',
    foot: 15,
    spots: {},
    shadow: { kind: 'oval', cx: 15, rx: 17, ry: 5.44 },
    ground: { w: 27, d: 27 },
    attached: [],
  },
  net: {
    id: 'net',
    w: 99,
    h: 38,
    base: 36,
    layer: 'ground',
    foot: 50,
    spots: {},
    ground: { w: 0, d: 0 },
    attached: [],
  },
  bucket: {
    id: 'bucket',
    w: 16,
    h: 18,
    base: 16,
    layer: 'stand',
    foot: 8,
    spots: {},
    shadow: { kind: 'oval', cx: 8, rx: 8, ry: 2.56 },
    ground: { w: 11, d: 11 },
    attached: [],
  },
  pine: {
    id: 'pine',
    w: 121,
    h: 238,
    base: 236,
    layer: 'stand',
    foot: 61,
    spots: {},
    shadow: { kind: 'oval', cx: 61, rx: 57, ry: 18.240000000000002 },
    ground: { w: 23, d: 23 },
    attached: [],
  },
  pine_2: {
    id: 'pine_2',
    w: 101,
    h: 200,
    base: 198,
    layer: 'stand',
    foot: 51,
    spots: {},
    shadow: { kind: 'oval', cx: 51, rx: 48, ry: 15.36 },
    ground: { w: 23, d: 23 },
    attached: [],
  },
  pine_3: {
    id: 'pine_3',
    w: 131,
    h: 276,
    base: 274,
    layer: 'stand',
    foot: 66,
    spots: {},
    shadow: { kind: 'oval', cx: 66, rx: 63, ry: 20.16 },
    ground: { w: 23, d: 23 },
    attached: [],
  },
  oak: {
    id: 'oak',
    w: 238,
    h: 260,
    base: 258,
    layer: 'stand',
    foot: 119,
    spots: {},
    shadow: { kind: 'oval', cx: 119, rx: 106, ry: 33.92 },
    ground: { w: 23, d: 23 },
    attached: [],
  },
  fence: {
    id: 'fence',
    w: 84,
    h: 44,
    base: 42,
    layer: 'stand',
    foot: 42,
    spots: {},
    shadow: { kind: 'wall', x0: 1, x1: 83, height: 38 },
    ground: { w: 57, d: 19 },
    attached: [],
  },
  bench: {
    id: 'bench',
    w: 63,
    h: 38,
    base: 36,
    layer: 'stand',
    foot: 32,
    spots: {},
    shadow: { kind: 'oval', cx: 32, rx: 34, ry: 10.88 },
    ground: { w: 57, d: 30 },
    attached: [],
  },
  planter: {
    id: 'planter',
    w: 36,
    h: 38,
    base: 36,
    layer: 'stand',
    foot: 18,
    spots: {},
    shadow: { kind: 'oval', cx: 18, rx: 19, ry: 6.08 },
    ground: { w: 30, d: 30 },
    attached: [],
  },
  bush: {
    id: 'bush',
    w: 59,
    h: 44,
    base: 42,
    layer: 'stand',
    foot: 30,
    spots: {},
    shadow: { kind: 'oval', cx: 30, rx: 30, ry: 9.6 },
    ground: { w: 23, d: 23 },
    attached: [],
  },
  boulder: {
    id: 'boulder',
    w: 63,
    h: 44,
    base: 41,
    layer: 'stand',
    foot: 32,
    spots: {},
    shadow: { kind: 'oval', cx: 32, rx: 34, ry: 10.88 },
    ground: { w: 53, d: 30 },
    attached: [],
  },
  rowboat: {
    id: 'rowboat',
    w: 135,
    h: 58,
    base: 54,
    layer: 'stand',
    foot: 68,
    spots: {},
    shadow: { kind: 'water', x0: 2, x1: 133 },
    ground: { w: 0, d: 0 },
    attached: [],
  },
  buoy: {
    id: 'buoy',
    w: 32,
    h: 48,
    base: 45,
    layer: 'stand',
    foot: 16,
    spots: {},
    shadow: { kind: 'water', x0: 2, x1: 30 },
    ground: { w: 0, d: 0 },
    attached: [],
  },
  wreck_rock: {
    id: 'wreck_rock',
    w: 200,
    h: 139,
    base: 135,
    layer: 'stand',
    foot: 100,
    spots: {},
    shadow: { kind: 'water', x0: 2, x1: 198 },
    ground: { w: 0, d: 0 },
    attached: [],
  },
  crab: {
    id: 'crab',
    w: 23,
    h: 15,
    base: 11,
    layer: 'stand',
    foot: 12,
    spots: {},
    shadow: { kind: 'oval', cx: 12, rx: 10, ry: 3.2 },
    ground: { w: 11, d: 11 },
    attached: [],
  },
  gull: {
    id: 'gull',
    w: 29,
    h: 13,
    base: 7,
    layer: 'above',
    foot: 15,
    spots: {},
    ground: { w: 0, d: 0 },
    attached: [],
  },
  tavern_smoke: {
    id: 'tavern_smoke',
    w: 49,
    h: 65,
    base: 62,
    layer: 'above',
    foot: 25,
    spots: {},
    ground: { w: 0, d: 0 },
    attached: [],
  },
  smithy_smoke: {
    id: 'smithy_smoke',
    w: 49,
    h: 65,
    base: 62,
    layer: 'above',
    foot: 25,
    spots: {},
    ground: { w: 0, d: 0 },
    attached: [],
  },
};
